variables:
  COMMON_IMAGE: iopsys/code-analysis:0.27
  DEBUG: 'TRUE'
  SOURCE_FOLDER: "./src"
  RUN_CPPCHECK: "cppcheck --enable=all --error-exitcode=1"

include:
  - project: 'iopsys/gitlab-ci-pipeline'
    file: '/static-code-analysis.yml'

stages:
    - static_code_analysis
    - unit_test
    - functional_test

run_unit_test:
    stage: unit_test
    image: ${COMMON_IMAGE}
    allow_failure: true
    script:
        - "./gitlab-ci/setup.sh"
        - "./gitlab-ci/unit-test.sh"

    artifacts:
        when: always
        paths:
            - /build/unit-coverage

run_functional_test:
    stage: functional_test
    image: ${COMMON_IMAGE}
    allow_failure: true
    script:
        - "./gitlab-ci/setup.sh"
        - "./gitlab-ci/functional-test.sh"

    artifacts:
        when: always
        paths:
            - coverage.xml
